// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: products.sql

package db

import (
	"context"
)

const getProductCount = `-- name: GetProductCount :one
SELECT COUNT(*) FROM products
LIMIT 1
`

func (q *Queries) GetProductCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getProductCountStmt, getProductCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductCountByOwner = `-- name: GetProductCountByOwner :one
SELECT COUNT(*) FROM products
WHERE shop_owner_id = $1 LIMIT 1
`

func (q *Queries) GetProductCountByOwner(ctx context.Context, shopOwnerID int64) (int64, error) {
	row := q.queryRow(ctx, q.getProductCountByOwnerStmt, getProductCountByOwner, shopOwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
